#! /bin/bash -e

tmux_window_names=("manager" "server" "edit" "test"  "dev" "stg" "workers" "prod" "kafka_worker")
tmux_window_names_length=${#tmux_window_names[@]}
git_pull=false
start_server=false
start_workers=false
start_kafka_worker=false
name="$(basename $PWD)"

while getopts ":gn:sw" opt; do
  case $opt in
    g)
      git_pull=true
      ;;
    n)
      name="$OPTARG"
      ;;
    s)
      start_server=true
      ;;
    w)
      start_workers=true
      ;;
    k)
      start_kafka_worker=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

echo "server (-s): $start_server"
echo "workers (-w): $start_workers"
echo "name: $name"

echo -e "\033];$name\007" # set iTerm tab title

tmux new-session -d -s "$name"
tmux rename-window ${tmux_window_names[0]}

for (( i=1; i<tmux_window_names_length; i++ )); do
  tmux new-window -n "${tmux_window_names[$i]}"
done

tmux select-window -t 6
tmux send-keys "cat Capfile" Enter

tmux select-window -t 8
tmux send-keys "cat Capfile" Enter

tmux select-window -t 3
tmux send-keys "vim ." Enter

if $git_pull; then
  tmux select-window -t 2
  tmux send-keys "git checkout master && git pull origin master" Enter
fi

if $start_kafka_worker; then
  tmux select-window -t 9
  tmux send-keys "script/kafka_worker" Enter
fi

if $start_workers; then
  tmux select-window -t 7
  tmux send-keys "script/worker" Enter
fi

if $start_server; then
  tmux select-window -t 2
  tmux send-keys "script/server" Enter
fi

tmux attach-session -t "$name"
