#! /bin/bash -e

function print_block {
  line_break="\n"
  border="\n====================================================================="
  printf $line_break$border$line_break
  printf "$1"
  printf $border$line_break$line_break
}

function join {
  local IFS="$1"
  shift
  echo "$*"
}


should_git_pull=true
should_run_all_containers=false
should_stop_containers=false
docker_containers=(
  "backofficeapi"
  "customsvc"
  "diablo"
  "diablopks"
  "diabloreturnssvc"
  "employeessvc"
  "feedssvc"
  "financesvc"
  "inventoriumapi"
  "leadallocationapi"
  "locationssvc"
  "membersapi"
  "memberssvc"
  "nordstromapi"
  "nordstromavailabilitysvc"
  "nordstromproductssvc"
  "nordstromwarehousesvc"
  "operationsapi"
  "productaddressessvc"
  "salesapi"
  "salesordersvc"
  "shippingsvc"
  "shoppingcartsvc"
  "taxgatewaysvc"
  "trunkclubpks"
  "warehousemanagementsvc"
)
docker_containers_length=${#docker_containers[@]}

if [ "$1" = "nopull" ] || [ "$2" = "nopull" ]; then should_git_pull=false; fi
if [ "$1" = "all" ] || [ "$2" = "all" ]; then should_run_all_containers=true; fi
if [ "$1" = "off" ] || [ "$2" = "off" ]; then should_stop_containers=true; fi

variables="should_git_pull: $should_git_pull
should_run_all_containers: $should_run_all_containers
should_stop_containers: $should_stop_containers"

print_block $variables

print_block "starting postgres server..."

pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

cd /Users/jackblandin/tc/service_manager
if $should_git_pull; then
  print_block "git pulling..."
  git pull
else
  print_block "skipping git pull"
fi

print_block "starting only preset containers"
sh ~/tc/service_manager/script/start $(join " " $docker_containers)
