#! /bin/bash -e

cd ~/dotfiles/repo_lib/ipython_memory_usage && python setup.py install && cd ~/dotfiles
npm install -g js-beautify
sudo chown $USER ~/.config # allows user to write to this directory (needed for karabiner elements)

