#! /bin/bash -e

function print_block {
  line_break="\n"
  border="\n====================================================================="
  printf $line_break$line_break$border$line_break
  printf "$1"
  printf $border$line_break$line_break
}


should_git_pull=true
should_run_all_containers=false
should_stop_containers=false
docker_containers=(
  "backofficeapi"             "bouncer"                 "customsvc"
  "diablo"                    "diabloreturnssvc"        "elasticsearch"
  "employeessvc"              "feedssvc"                "financesvc"
  "identityapi"               "inventoriumapi"          "membersapi"
  "memberssvc"                "nginx"                   "nordstromapi"
  "nordstromavailabilitysvc"  "nordstromproductssvc"    "nordstromwarehousesvc"
  "operationsapi"             "postgres"                "productaddressessvc"
  "productssvc"               "salesapi"                "salesordersvc"
  "shoppingcartsvc"           "taxgatewaysvc"           "warehousemanagementsvc"
)
docker_containers_length=${#docker_containers[@]}
variables="should_git_pull: $should_git_pull
should_run_all_containers: $should_run_all_containers
should_stop_containers: $should_stop_containers"

if [ "$1" = "nopull" ] || [ "$2" = "nopull" ]; then should_git_pull=false; fi
if [ "$1" = "all" ] || [ "$2" = "all" ]; then should_run_all_containers=true; fi
if [ "$1" = "off" ] || [ "$2" = "off" ]; then should_stop_containers=true; fi

print_block $variables

print_block "starting postgres server..."

pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start

cd /Users/jackblandin/tc/service_manager
if $should_git_pull; then 
  print_block "git pulling..."
  git pull
else
  print_block "skipping git pull"
fi

print_block "starting vagrant..."

vagrant up

print_block "starting and updating all containers"
bundle exec rake start:update
if [ $should_run_all_containers = false ] || [ $should_stop_containers = true ]; then
  print_block "stopping all containers"
  bundle exec rake stop
  if [ $should_run_all_containers = false ]; then
    print_block "starting only preset containers"
    for (( i=1; i<docker_containers_length; i++))
    do
      bundle exec rake start "${docker_containers[$i]}"
    done
  fi
fi
