#! /bin/bash

ln -s ~/dotfiles/jdb_solarized_dark.vim ~/.vim/bundle/lightline.vim/autoload/lightline/colorscheme/jdb_solarized_dark.vim
ln -s ~/dotfiles/zsh/zshenv ~/.zshenv
ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
ln -s ~/dotfiles/python/jupyter_notebook_config.py ~/.jupyter/jupyter_notebook_config.py
ln -s ~/dotfiles/slate/slate ~/.slate
ln -s ~/dotfiles/agignore ~/.agignore
ln -s ~/dotfiles/git/global_gitignore ~/.gitignore_global
ln -s ~/dotfiles/karabiner ~/.config
ln -s ~/dotfiles/jackblandin.zsh-theme ~/.oh-my-zsh/themes/jackblandin.zsh-theme
ln -s ~/dotfiles/tmux/tmux.conf.local ~/.tmux.conf.local
