#! /bin/bash -e

name="$1"
if [ -z "$1" ]; then
  name="$(basename $PWD)"
fi

tmux_window_names=("git" "run/test" "edit" "ssh")
tmux_window_names_length=${#tmux_window_names[@]}

echo -e "\033];$name\007" # set iTerm tab title

tmux new-session -d -s "$name"
tmux rename-window ${tmux_window_names[0]}

for (( i=1; i<tmux_window_names_length; i++ ))
do
  echo ${tmux_window_names[$i]}
  tmux new-window -n "${tmux_window_names[$i]}"
done

tmux attach-session -t "$name"
