#! /bin/bash -e

if [ ! -e "/Users/jackblandin/dotfiles/.slate" ]; then
  ln -s ~/dotfiles/.slate ~/.slate
fi

if [ ! -e "/Users/jackblandin/dotfiles/themes/agnoster.zsh-theme" ]; then
  ln -s ~/dotfiles/themes/agnoster.zsh-theme ~/.oh-my-zsh/themes/my-agnoster.zsh-theme
fi
